import "@/assets/style.scss"
import type { Metadata } from "next"
import Footer from "./()/footer"
import Header from "./()/header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <div className="grow">{children}</div>
      <Footer />
    </>
  )
}
